apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 1m0s
  sourceRef:
    kind: Snapshot
    name: podinfo-deployment
    namespace: ocm-system
  configRef:
    componentVersionRef:
      name: podinfo
      namespace: ocm-system
    resource:
      name: config
  snapshotTemplate:
    name: podinfo-deployment-localized
    tag: latest